version: 2
jobs:
  build:
    docker:
      - image: node:11
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: npm install
      - run:
          name: Running Tests
          command: npm test
